### ISSUE TITLE
plan.io integration for Slack

### ISSUE THREAD

**Issue by zupo** [niteoweb/ostasks#4]
User story: For every message in Slack that contains an issue number (example: #1234), post the message as a comment on that issue. The comment should link back to the slack message, so that from the issue you can easily get to the Slack conversation about the issue.

**Comment by JanLikar** [comment]
So, creating a Slack bot is the way to go?

Edit: Also, how is this going to be deployed?

**Comment by zupo** [comment]
Have not really done any research on this, but I would presume:
1. yes
2. My preferred way is a pyramid app, deployed to Heroku. I'm gonna create one app for you now and give you access. If you need any addons (DB, etc.), write here and I'll add them.

**Comment by zupo** [comment]
Not using plan.io any more.
