### ISSUE TITLE
flake8_tuple support for deform Buttons

### ISSUE THREAD

**Issue by zupo** [niteoweb/ostasks#6]
flake8_tuple reports the last line in 

```python
class ReferralsView(FormView):  # !qa: D101
    schema = ReferralsSchema()
    buttons = (Button(name='send_invites', title='Send Invites'), )
```

For me, this is a false positive. A line like such is less readable as the trailing comma indicates a listing:
```python
class ReferralsView(FormView):  # !qa: D101
    schema = ReferralsSchema()
    buttons = (Button(name='send_invites', title='Send Invites'))
```

That said, I see cases where such a check can find potential errors. Such as `foo = 'bar',`, so I would still like to have this linter in. Maybe we can fix the problem upstream?

**Comment by zupo** [comment]
It's been almost two years since this bug report. We first need to verify the bug still exists.

**Comment by mandarvaze** [comment]
I confirm that the "bug" still exists.

flake_tuple specifically checks for such case. See [this](https://github.com/ar4s/flake8_tuple/blob/master/tests/test_pep8_tuple.py#L15)

I also confirmed that the error "goes away" on adding `# noqa` to the line.

i.e. Keep the linter to catch `foo = 'bar',` type scenario, and use `# noqa` for "False positives" (The way flake8_tuple is designed it is **not** a False positive)

**Comment by zupo** [comment]
We've completely adopted https://github.com/python/black since the issue was created, making any styling discussions irrelevant & obsolete. Yay!
